# Generated by Django 4.2.4 on 2023-08-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('started_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ends_on', models.DateTimeField(auto_now=True, null=True)),
                ('donation_title', models.CharField(max_length=256)),
                ('donation_minimum_amount', models.IntegerField(default=0)),
                ('donation_status', models.SmallIntegerField(default=0)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_donation_header',
            },
        ),
        migrations.CreateModel(
            name='DonationInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('donation_inquiry_type', models.CharField(max_length=10)),
                ('donation_inquiry_content', models.CharField(max_length=1024)),
                ('donation_inquiry_status', models.SmallIntegerField(default=0)),
                ('donation_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationheader')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_donation_inquiry',
            },
        ),
        migrations.CreateModel(
            name='DonationReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('donation_reply_content', models.CharField(max_length=1024)),
                ('donation_status', models.SmallIntegerField(default=0)),
                ('donation_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationheader')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_donation_reply',
            },
        ),
        migrations.CreateModel(
            name='DonationInquiryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('donation_inquiry_answer_content', models.CharField(max_length=1024)),
                ('donation_inquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationinquiry')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_donation_inquiry_answer',
            },
        ),
        migrations.CreateModel(
            name='DonationDoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_amount', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('donation_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationheader')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_donation_doner',
            },
        ),
        migrations.CreateModel(
            name='DonationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_description', models.CharField(max_length=256)),
                ('donation_content', models.CharField(max_length=10240)),
                ('donation_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationheader')),
            ],
            options={
                'db_table': 'tbl_donation_detail',
            },
        ),
    ]
