# Generated by Django 4.2.4 on 2023-08-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_rename_donation_header_id_donationdetail_donation_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationdoner',
            old_name='donation_header_id',
            new_name='donation_header',
        ),
        migrations.RenameField(
            model_name='donationdoner',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='donationheader',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='donationinquiry',
            old_name='donation_header_id',
            new_name='donation_header',
        ),
        migrations.RenameField(
            model_name='donationinquiry',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='donationinquiryanswer',
            old_name='donation_inquiry_id',
            new_name='donation_inquiry',
        ),
        migrations.RenameField(
            model_name='donationinquiryanswer',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='donationreply',
            old_name='donation_header_id',
            new_name='donation_header',
        ),
        migrations.RenameField(
            model_name='donationreply',
            old_name='member_id',
            new_name='member',
        ),
    ]
