# Generated by Django 4.2.4 on 2023-08-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('started_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ends_on', models.DateTimeField(auto_now=True, null=True)),
                ('campaign_header_title', models.CharField(max_length=256)),
                ('campaign_header_category', models.CharField(max_length=100)),
                ('campaign_header_description', models.CharField(max_length=100)),
                ('campaign_status', models.SmallIntegerField(default=0)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_campaign_header',
            },
        ),
    ]
