# Generated by Django 4.2.4 on 2023-08-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='city_detail_id',
            new_name='city_detail',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='city_header_id',
            new_name='city_header',
        ),
    ]
