# Generated by Django 4.2.4 on 2023-08-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('started_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ends_on', models.DateTimeField(auto_now=True, null=True)),
                ('funding_title', models.CharField(max_length=256)),
                ('funding_minimum_amount', models.IntegerField(default=0)),
                ('funding_status', models.SmallIntegerField(default=0)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_funding_header',
            },
        ),
        migrations.CreateModel(
            name='FundingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('funding_inquiry_type', models.CharField(max_length=10)),
                ('inquiry_content', models.CharField(max_length=10240)),
                ('inquiry_status', models.SmallIntegerField(default=0)),
                ('funding_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.fundingheader')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_funding_inquiry',
            },
        ),
        migrations.CreateModel(
            name='FundingSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_amount', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('funding_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.fundingheader')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_funding_sponsor',
            },
        ),
        migrations.CreateModel(
            name='FundingReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('funding_reply_content', models.CharField(max_length=1024)),
                ('funding_status', models.SmallIntegerField(default=0)),
                ('funding_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.fundingheader')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_funding_reply',
            },
        ),
        migrations.CreateModel(
            name='FundingInquiryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('funding_inquiry_answer_content', models.CharField(max_length=1024)),
                ('funding_inquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.fundinginquiry')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_funding_inquiry_answer',
            },
        ),
        migrations.CreateModel(
            name='FundingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_description', models.CharField(max_length=256)),
                ('funding_content', models.CharField(max_length=10240)),
                ('funding_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.fundingheader')),
            ],
            options={
                'db_table': 'tbl_funding_detail',
            },
        ),
    ]
